'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _lwc = require('lwc');

var _cChildComponent = require('c/childComponent');

var _cChildComponent2 = _interopRequireDefault(_cChildComponent);

describe('c-child-component', function () {
    afterEach(function () {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', function () {
        // Arrange
        var element = (0, _lwc.createElement)('c-child-component', {
            is: _cChildComponent2['default']
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});